### ISSUE TITLE
Factors integration

### ISSUE THREAD

**Issue by merc85garcia** [lium-lst/nmtpy#15]
-    metrics for lemma and factors printed in mainloop.py
-    test weight decay

**Comment by merc85garcia** [comment]
Ensambling with factors

**Comment by merc85garcia** [comment]
Run valid_save_hyp option with factors and avoid the temp files

**Comment by merc85garcia** [comment]
weight_decay and dropout

**Comment by ozancaglayan** [comment]
I think we can close this, right?

**Comment by merc85garcia** [comment]
the first comment is done, the other 3 no.

**Comment by merc85garcia** [comment]
- Run valid_save_hyp option with factors without editing mainloop.py
- metrics for lemma and factors printed in mainloop.py

**Comment by merc85garcia** [comment]
- metrics for lemma and factors printed in mainloop.py
- test weight decay

**Comment by ozancaglayan** [comment]
can this be closed?
