### ISSUE TITLE
Validations in a separate folder + decode validation at the end of training

### ISSUE THREAD

**Issue by loicbarrault** [lium-lst/nmtpy#17]
- [x] put `valid_hyps` into a separate folder. e.g. `models/model_name.valid_hyps`
- [x] before exiting `nmt-train`, perform a last call to `nmt-translate` with the best system and tag it **.BEST**

**Comment by ozancaglayan** [comment]
For the second, we can just copy the best file with a new filename. Or do you seen an interest in doing the decoding again?

**Comment by loicbarrault** [comment]
yes you are right, copy or *link* (even better)

**Comment by ozancaglayan** [comment]
Merged.
