### ISSUE TITLE
Character-based NMT

### ISSUE THREAD

**Issue by wuhaixutab** [lium-lst/nmtpy#32]
Do you or will you implement character-based translation?

**Comment by ozancaglayan** [comment]
Hello,

There's actually not much to implement for character-based NMT. I just pushed a script called `scripts/prep-charnmt.sh` which processes a dataset in a way to tokenize the characters and then calls `nmt-build-dict` to build the vocabulary files.

Finally, you need to add `filter: char2words` in your experiment configuration file to let `nmt-translate` correctly post-process the char-based outputs into word forms. This will allow correct BLEU, METEOR computation during early-stopping.

Let me know if you encounter any problems.
